autenti/urls.py
from django.urls import path
from .views import VRegistro, cerrar_sesion, logeo

app_name= 'autenti'

urlpatterns=[
    path("", VRegistro.as_view(), name="registro"),
    path("cerrar-sesion/", cerrar_sesion, name="cerrar_sesion"),
    path("login/", logeo, name="logeo"),
    ]

blog/urls.py
from django.urls import path
from .views import contacto, buscar, post_detail, postcategory, prueba, privacidad, sobre_mi

app_name= 'blog'

urlpatterns=[
    path("", prueba, name="bloghome"),
    path("post/<int:post_id>", post_detail, name="post_detail"),
    path("privacidad/", privacidad, name = "privacidad"),
    path("posts/", postcategory, name = "allposts"),
    path("categoria/", buscar, name = "postcategory"),
    path("about-me/", sobre_mi, name = "about-me"),
    path("contact/", contacto, name="contact"),
    ]

donations/urls.py
from django.urls import path
from .views import donation

app_name= 'donations'

urlpatterns=[
    path("",donation, name="donation"),

    ]

projectblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from tienda.sitemap import TiendaViewSitemap
from blog.sitemaps import PostSitemap
sitemaps = {
    "posts": PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('registro/', include('autenti.urls')),
    path('donaciones/', include('donations.urls')),
    path('tienda/', include('tienda.urls')),
    path('api/v1.0/', include('projectblogapi.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path
from .views import EjemploTienda, VerImagenes, ver_imagen
#from .views_agregar import agregar

app_name= 'tienda'

urlpatterns=[
    path("", EjemploTienda.as_view(), name="ejemplo_tienda"),
    path('verimagenes/', VerImagenes.as_view(), name="verimagenes"),
    path('<int:producto_id>/ver/', ver_imagen, name="ver"),
    ]

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.conf import settings
from django.urls import reverse




#modelo base para heredar
class ModeloBase(models.Model):
    id=models.AutoField(primary_key=True)
    estado= models.BooleanField('Estado', default=True)
    fecha_creacion=models.DateField('Fecha de Creación', auto_now=False, auto_now_add=True)
    fecha_modificacion=models.DateField('Fecha de Modificación', auto_now=True, auto_now_add=False)
    fecha_eliminacion=models.DateField('Fecha de eliminación', auto_now=True, auto_now_add=False)  


    class Meta:
        abstract= True #la clase abstracta permite no mandar esto a la db, sino que agregarlas donde lo requiramos


#modelo de categoria
class Categoria(ModeloBase):
    nombre= models.CharField('Nombre de la Categoria', max_length=100, unique=True)
    imagen_referencial=models.ImageField('Imagen Referencial', upload_to='categoria/images/')

    class Meta:
        verbose_name= "Categoria"
        verbose_name_plural= "Categorias"

    def __str__(self):
        return self.nombre

#modelo de autor
class Autor(ModeloBase):
    nombre= models.CharField("Nombres", max_length=100)
    apellidos=models.CharField("Apellidos", max_length=120)
    email=models.EmailField("Correo Electrónico", max_length=150)
    descripcion=models.TextField("Descripción")
    web=models.URLField("Web", null=True, blank=True)
    linkedin=models.URLField("LinkedIn", null=True, blank=True)
    github=models.URLField("GitHub", null=True, blank=True)
    img = models.ImageField('Imagen Referencial', null = True, blank = True,upload_to = 'blog/images/autores/')

    class Meta:
        verbose_name= "Autor"
        verbose_name_plural= "Autores"

    def __str__(self):
        return "{1} {0}".format(self.apellidos,self.nombre)

#modelo de posts
class Post(ModeloBase):
    titulo=models.CharField("Titulo del Post", max_length=150, unique=True)
    slug=models.CharField("Slug", max_length=150, unique=True)
    descripcion=models.TextField("Descripción")
    autor=models.ForeignKey(Autor, on_delete=models.CASCADE)
    categoria=models.ForeignKey(Categoria,on_delete=models.CASCADE)
    contenido=RichTextField()
    img=models.ImageField(upload_to="blog/images/", max_length=255)
    publicado= models.BooleanField("Publicado/No Publicado", default=False)
    fecha_publicacion= models.DateField("Fecha publcación")


    class Meta:
        verbose_name= "Post"
        verbose_name_plural= "Posts"

    def __str__(self):
        return self.titulo
    
    def get_absolute_url(self):
        return f"/post/{self.titulo}/"


class Web(ModeloBase):
    nosotros=models.TextField("Nosotros")
    email=models.EmailField("Correo Electrónico", max_length=150)

    class Meta:
        verbose_name= "Web"
        verbose_name_plural= "Webs"

    def __str__(self):
        return self.nosotros


class RedesSociales(ModeloBase):
    instagram=models.URLField("Instagram")
    linkedin=models.URLField("LinkedIn", null=True, blank=True)
    stackoverflow=models.URLField("Stackoverflow", null=True, blank=True)


    class Meta:
        verbose_name="Red Social"
        verbose_name_plural="Redes Sociales"

    def __str__(self):
        return self.linkedin


#########
#modelo de contacto
class Contacto(ModeloBase):
    nombre= models.CharField("Nombre", max_length=150)
    apellido=models.CharField("Apellido", max_length=150)
    correo=models.EmailField("Correo Electrónico", max_length=150)
    asunto=models.CharField("Asunto", max_length=200)
    mensaje=models.TextField("Mensaje")

    class Meta:
        verbose_name= "Contacto"
        verbose_name_plural= "Contactos"

    def __str__(self):
        return self.asunto

#modelo de subscriptor
class Subscriptor(ModeloBase):
    correo=models.EmailField("Correo Electrónico", max_length=150)
    
    class Meta:
        verbose_name= "Subscriptor"
        verbose_name_plural= "Subscriptores"
    
    def __str__(self):
        return self.correo

donations/models.py
from django.db import models

# Create your models here.

tienda/models.py
from django.db import models

# Create your models here.

class Saludos(models.Model):
    tipo = models.CharField(max_length=40)
    img= models.ImageField(upload_to="tienda/images/", max_length=255)

class CategoriaBebidas(models.Model):
    tipo= models.CharField(max_length=20)

    def __str__(self):
        return self.tipo

class Producto(models.Model):
    nombre= models.CharField(max_length=20)
    img= models.ImageField(upload_to="tienda/images/", max_length=255)
    categoria= models.ForeignKey(CategoriaBebidas, on_delete=models.CASCADE)
    saludable= models.BooleanField(default=False)

    def __str__(self):
        return self.nombre

blog/forms.py
from django import forms

class FormularioContacto(forms.Form):
    nombre=forms.CharField(label='Nombre', required=True, max_length=20)
    email=forms.CharField(label='Email', required=True, max_length=30)
    contenido=forms.CharField(label='Contenido', max_length=400, widget=forms.Textarea)

blog/views.py
import random
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from django.contrib.contenttypes.models import ContentType
from .models import Categoria, Post
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.template import loader
from .forms import FormularioContacto
from django.http import Http404
from django.views.generic import View

def prueba(request):
    postsindex= Post.objects.all().order_by("fecha_publicacion")
    return render(request, "home.html", {'postsindex':postsindex})

#detalles del post
def post_detail(request, post_id):
    posts=get_object_or_404(Post, pk=post_id)
    return render(request, "post_detail.html", {"post":posts})

#template privacidad
def privacidad(request):
    return render(request, "privacidad.html")

#busqueda por categoria
def postcategory(request):
    postsindex= Post.objects.all().order_by("fecha_publicacion")
    return render(request, "all_posts.html", {'postsindex':postsindex})

#busqueda por query set = categoria 
def buscar(request):
    qs= request.GET.get("category")
    
    if request.GET.get("category"):
        categoria= request.GET.get("category")
        postsindex= Post.objects.filter(categoria = Categoria.objects.get(nombre= categoria))
    else:
        postsindex= Post.objects.all().order_by("fecha_publicacion")
    return render(request, "all_posts.html", {'postsindex':postsindex})

#template sobre mi
def sobre_mi(request):
    postsindex= Post.objects.all().order_by("fecha_publicacion")
    return render(request, "about_me.html", {'postsindex':postsindex})

#form contacto
def contacto(request):
    formulario_contacto= FormularioContacto(data=request.POST)
    if formulario_contacto.is_valid():
        nombre=request.POST.get("nombre")
        email=request.POST.get("email")
        contenido=request.POST.get("contenido")
        email=EmailMessage("Mensaje desde Techmig",
        "El usuario con nombre {} con la dirección {} escribe lo siguiente: \n\n {}".format(nombre,email,contenido),
        "",
        ["devmigliaccio@gmail.com"],
        reply_to=[email])
        try:
            email.send()
            return redirect("/?valido")
        except:
            return redirect("/?novalido")
    return render(request, "contact/contact.html", {"miFormulario":formulario_contacto})

donations/views.py
from django.shortcuts import render

# Create your views here.

def donation(request):
    return render (request, "donation.html")

tienda/views.py
from django.http import Http404
from django.shortcuts import render
from django.views.generic import View
from .models import Producto
# Create your views here.

class EjemploTienda(View):
    template= "tienda.html"

    def get(self, request):
        params={}
        try:
            productos = Producto.objects.all()
        except Producto.DoesNotExist:
            raise Http404
        params ["productos"] = productos

        try:
            request.session["carro"]
        except:
            request.session["carro"] = {}


        return render(request, self.template, params)


class VerImagenes(View): 
    template = "verimagenes.html"

    def get(self, request):
        params={}
        try:
            productos = Producto.objects.all()
        except Producto.DoesNotExist:
            raise Http404
        params["productos"] = productos
        
        return render(request, self.template, params)


def ver_imagen(request, producto_id):
    params={}
    try:
        producto = Producto.objects.get(pk=producto_id)
    except Producto.DoesNotExist:
        raise Http404
    params["producto"] = producto
    
    return render(request, "verimagen.html", params)

blog/templates/all_posts.html
{% extends 'index.html' %}

{% load static %}

{% block content %}
<section id="main">


<div class="container">
    <div class="col-12">
            <form method="get">
            <div class="row">
                <div class="col col-md-8">
                    <input type="text" placeholder="Buscar Categoría..." name="category">
                    
                </div>
                <div class="col col-md-4">
                    <input type="submit" value="Buscar">
                </div>
            </div>
            <br><br>
            
            </form>
        <!-- Blog -->
            <section>
                <header class="major">
                    <h2>Todos los Posts</h2>
                </header>
                <div class="row">
                    {% for post in postsindex %}
                    <div class="col-6 col-12-small">
                        <section class="box">
                            {% if post.img %}
                            <a href="#" class="image featured"><img src='{{post.img.url}}' alt="{{post.titulo}}" style="max-width: 800px; max-height: 1000px;"/></a>
                            {% endif %}
                            <header>
                                <h3>{{post.titulo}}</h3>
                                <p>{{post.categoria}}</p>
                            </header>
                            <p>{{post.descripcion|striptags|truncatechars:200}}</p>
                            <footer>
                                <ul class="actions">
                                    <li><a href="{% url 'blog:post_detail' post.id %}" class="button icon solid fa-file-alt">Continuar Leyendo</a></li>
                                    <li><a href="{% url 'blog:post_detail' post.id %}#disqus_thread" class="button alt icon solid fa-comment"></a></li>
                                </ul>
                            </footer>
                        </section>
                    </div>
                    {% endfor %}
                </div>
            </section>
            
    </div>
</div>

</section>
<script id="dsq-count-scr" src="//techmig.disqus.com/count.js" async></script>

{% endblock %}     

blog/templates/home.html
{% extends 'index.html' %}

{% load static %}

{% block content %}

<!-- Banner -->
<section id="banner">
    <header>
        <h2>El mejor blog de tecnología.</h2>
        <p>Con respuestas a todo tipo de problemas</p>
    </header>
</section>
<br><br>
<!-- Intro -->
<section id="intro" class="container">
    <div class="container">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">    
                <div class="carousel-item active">         
                    <img class="d-block w-100" src="{% static 'images/More Trust More Fast.jpg' %}" alt="banner 1">
                    <h1>Post</h1>
                </div>
                
                {% for post in postsindex %}
                <div class="carousel-item">
                    {% if post.img %}
                    <img class="d-block w-100" src="{{post.img.url}}" alt="banner 3" style="height: 500px; width: 1200px;">
                    {% endif %}
                    <br>
                    <a href="{% url 'blog:post_detail' post.id %}" class="button large">{{post.titulo}}</a>
                    <div class="col col-md-3">
                        <figure class="author-figure mb-0 mr-3 float-left"><img src="{{ post.autor.img.url }}" alt="Image" class="img-circle" style="height: 50px;width: 50px;border-radius: 35px;"><strong>&nbsp;&nbsp;{{post.autor}}</strong></figure>
                        <h3 class="my-2 h5 text-muted" style="font-size: 14px;">{{post.fecha_publicacion|date:'F jS Y'}}</h3>
                    </div>
                </div>
                {% endfor %}
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <footer>
            <ul class="actions">
                <li><a href="{% url 'blog:allposts' %}" class="button large">Ver todos los Posts</a></li>
                <li><a href="https://lucasmiglia.pythonanywhere.com/" target="_blank" class="button alt large">Más sobre mí</a></li>
            </ul>
        </footer>
    </div>
    
</section>



<!-- Main -->
<section id="main">
<div class="container">
<div class="row">
    <div class="col-12">

        <!-- Portfolio -->
<section  id="postscards">    
            
                <header class="major">
                    <h2>Últimos Posts</h2>
                </header>
                <div class="row">
                    {% for post in postsindex %}
                    <div class="col-4">
                            <div class="card">

                                <div class="card-header" style="background-color: #CF2C4E;color:whitesmoke;margin: auto;">
                                    <h5 class="card-title" style="margin: auto;">{{post.titulo}}</h5>
                                </div>
                                {% if post.img %}
                                <img src="{{post.img.url}}" alt="{{post.titulo}}" class="img-top"/>
                                {% endif %}
                                <div class="card-body">
                                    <p style="color: darkslategrey;">{{post.descripcion|striptags|truncatechars:100}}</p>
                                </div>

                                <div class="card-footer" style="background-color: #CF2C4E;">
                                    <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary btn-lg btn-block" style="
                                        background-color: #CF2C4E;
                                        border-color:#BF1C3E;
                                        font-family: inherit;
                                        ">Ver más</a> 
                                    
                                </div>

                            </div>

                            
                    </div>
                    {% endfor %}
                    
                </div>
                
                
                        
</section>                 
<div class="container" style="text-align: center;">
    <a href="{% url 'blog:allposts' %}" class="button large">Ver todas las publicaciones</a>
</div>    


    </div>
</div>
</div>
</section>

{% endblock %}

blog/templates/index.html
{% load static %}

<!DOCTYPE HTML>
<html>
	<head>
		<title>Lucas BLOG</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes" />
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
		<link rel="stylesheet" href= "{% static 'assets/css/main.css' %}" />
		<link rel="stylesheet" href= "{% static 'assets/js/jquery.scrollex.min.js' %}" />
		<link rel="stylesheet" href= "{% static 'assets/js/jquery.min.js' %}" />
		<link rel="stylesheet" href= "{% static 'assets/js/jquery.dropotron.min.js' %}" />

	</head>
	<body class="homepage is-preload">
		{% block scripts %}
		
		{% endblock %}
		<div id="page-wrapper">

			<!-- Header -->
				<section id="header">

					<!-- Logo -->
						<h1><a href="/">TECHMIG</a></h1>

					<!-- Nav -->
						<nav id="nav">
							<ul>
								<li class="current"><a href="{% url 'blog:bloghome' %}">Home</a></li>
								<li><a href="{% url 'blog:allposts' %}">Posts</a></li>
								<li>
									<a href="#">Información</a>
									<ul>
										<li><a href="{% url 'blog:about-me' %}">Preguntas Frecuentes</a></li>
										<li><a href="{% url 'blog:about-me' %}">Sobre mí</a></li>
										<li><a href="{% url 'blog:contact' %}">Contacto</a></li>
										<li><a href="{% url 'donations:donation' %}">Donaciones</a></li>
									</ul>
								</li>
								<li><a href="{% url 'blog:privacidad' %}">Términos de Privacidad</a></li>
							</ul>
						</nav>
						<br>
						<div style="text-align: right; margin-right:100px;">
							{% if user.is_authenticated %}
							<a href="#" style="color: red;">{{user.username}}</a>&nbsp;<a href="{% url 'autenti:cerrar_sesion' %}"><button type="button" class="btn btn-dark" style="
								background-color: #CF2C4E;
								border-color:#BF1C3E;
								font-family: inherit;">Cerrar Sesión</button></a> 
							
							{% else %}
							<a href="{% url 'autenti:logeo' %}"><button type="button" class="btn btn-dark" style="
							background-color: #CF2C4E;
							border-color:#BF1C3E;
							font-family: inherit;">Ingresar</button></a>
							<a href="{% url 'autenti:registro' %}"><button type="button" class="btn btn-dark" style="
							background-color: #CF2C4E;
							border-color:#BF1C3E;
							font-family: inherit;">Registrarse</button></a>
							
							{% endif %}
						</div>
						
							
				</section>
						{% block content %}


						{% endblock %}

						{% include 'partials/footer.html'%}
			<!-- Footer -->
				
		<!-- Scripts -->
			<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.dropotron.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>
			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

			<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

			<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
			<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>

	</body>
</html>

blog/templates/login.html
{% extends "index.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="container" >

        <form action="" method="post" style="margin: 10px; color: darkgrey;">
            {% csrf_token %}
    
            {{form|crispy}} 
            
            <br><br>
            <button type="submit" class="btn btn-success" style="
            background-color: #CF2C4E;
            border-color:#BF1C3E;
            font-family: inherit;"> ¡Logueate! </button>
            
            
            <br>
    
        </form>

        
    </div>


{% endblock %} 

blog/templates/post_detail.html
{% extends 'index.html' %}

{% load static %}

{% block content %}
<link rel="stylesheet" href= "{% static 'assets/css/main.css' %}" />
			<!-- Main -->
				<section id="main">
					<div class="container">

						<!-- Content -->
							<article class="box post" itemscope itemtype="http://schema.org/BlogPosting">
								<a href="#" class="image featured"></a>
								<header>
									<h2 itemprop="headline">{{post.titulo}}</h2>
									<p itemprop="author">Autor: {{post.autor}}</p>
									<p itemprop="datePublished">Fecha: {{post.fecha_publicacion}}</p>	
									<p itemprop="articleSection">Categoria: {{post.categoria}}</p>
									<p itemprop="description">{{post.descripcion}}</p>
								</header>
							
								<section>
									<div class="contenido" itemprop="articleBody"> 
										{{post.contenido|safe}}
									</div>
								</section>
							</article>

					</div>
				</section>
				<section id="comentario_section">

					<div class="container">
						<h2 style="text-align: center;"><strong>Comentarios</strong></h2>
						<br> <br>

						<div id="disqus_thread"></div>
							<script>
								/**
								*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
								*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
								/*
								var disqus_config = function () {
								this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
								this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
								};
								*/
								(function() { // DON'T EDIT BELOW THIS LINE
								var d = document, s = d.createElement('script');
								s.src = 'https://techmig.disqus.com/embed.js';
								s.setAttribute('data-timestamp', +new Date());
								(d.head || d.body).appendChild(s);
								})();
							</script>
							<script id="dsq-count-scr" src="//techmig.disqus.com/count.js" async></script>
							<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
					</div>
					
					
					
						
					<p><strong></strong></p>
				</section>
{% endblock %}

blog/templates/register.html
{% extends "index.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="container" >

        <form action="" method="post" style="margin: 10px; color: darkgrey;">
            {% csrf_token %}
    
            {{form|crispy}} 
            
            <br><br>
            <button type="submit" class="btn btn-success" style="
            background-color: #CF2C4E;
            border-color:#BF1C3E;
            font-family: inherit;"> ¡Registrarse! </button>
            
            
            <br>
    
        </form>

        
    </div>


{% endblock %} 

blog/templates/tienda.html
{% extends 'index.html' %}

{% load static %}

{% block content %}
<br>  
  <div class="container">
    <div class="row">
        <br> 
        <section  id="postscards">
            <div class="card" style="padding: 15px;">
        {% for producto in productos %}
        <div class="col-12 col-md-4" itemscope itemtype="http://schema.org/Product">
                <div class="container" style="text-align: center;">
                    <h2 class="card-title">{{producto.nombre}}</h2>
                </div>
                <a href="{% url 'tienda:ver' producto.id%}">
                    <img src="{{producto.img.url}}" style="width: 350px; height: 420px;" class="img-top"/>
                </a>
                    <input type="submit"  hidden class="col-12 vervalor" value="1"/>
                    <input type="submit"  hidden class="col-12 verid" value="utn_{{producto.id}}"/> <br><br>
                <div class="card-footer" style="background-color: #CF2C4E;">
                    <button type="button" class="btn btn-primary btn-lg btn-block" style="
                    background-color: #CF2C4E;
                    border-color:#BF1C3E;
                    font-family: inherit;
                    " name="agregar">Agregar</button>
                </div>

        </div>
        {% endfor %}
        </div><br>   
        </section>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script> 
    <script>
        /*jslint browser: true*/
        /*jslint plusplus: true*/
        /*global FormData: false */
        /*global $, jQuery, alert, console*/
        /*..............................................................................................
        ... PARA VALIDAR LOS DATOS .....................................................
        .............................................................................................*/
        var csrftoken = $.cookie('csrftoken');
        function csrfSafeMethod(method) {
            "use strict";
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        };

        $('.agregar').click( 
            function (event) {
            
                event.preventDefault();
                
                
                let cada_producto_id= $(this).parent().find('.verid').val();
                let valor=$(this).parent().find('.vervalor').val();
                console.log(cada_producto_id);
                console.log(valor);

                console.log(JSON.stringify(localStorage));
                let i;
                for(i = 0; i < localStorage.length; i++){
                    let clave_eliminar= localStorage.key(i);
                    console.log("bbbbbbbbbbbbbbbbbbbbbbbbb")
                    console.log(typeof clave_eliminar);
                    console.log(clave_eliminar);
                    if (!clave_eliminar.startsWith("utn_")){
                        console.log("retorna NO verdadero!!!!");
                        localStorage.removeItem(clave_eliminar);
                        console.log("retorna NO verdadero!!!!");
                    }
                    }
                }
        );
</script> 

{% endblock %}

{% block scripts %}
    <script src="https://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script> 
{% endblock %}

blog/templates/verimagen_post.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            {% for producto in productos %}
                <a href="{% url 'blog:ver' post.id %}">
                    <p> {{post.nombre}}</p>
                    <img src="/media/{{post.img}}" style="width: 30%;"/>
                </a>
            {% endfor %}
        </div>
    </div>
  </div>
{% endblock  %}

blog/templates/verimagenes.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            {% for producto in productos %}
                <a href="{% url 'tienda:ver' producto.id %}">
                    <p> {{producto.nombre}}</p>
                    <img src="/media/{{producto.img}}" style="width: 30%;"/>
                </a>
            {% endfor %}
        </div>
    </div>
  </div>
{% endblock  %}